// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``
/// `

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGNwBkKYRY0l-JUbA_aKg8iVmgmamqoo',
    appId: '1:36974916364:web:46603ffe9b4835c42c4f29',
    messagingSenderId: '36974916364',
    projectId: 'fir-bolt-app',
    authDomain: 'fir-bolt-app.firebaseapp.com',
    storageBucket: 'fir-bolt-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_0oXDMaLEW3sbvpB380CmKGTZbui1Aoc',
    appId: '1:36974916364:android:483b9e97161e65d72c4f29',
    messagingSenderId: '36974916364',
    projectId: 'fir-bolt-app',
    storageBucket: 'fir-bolt-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjyA1hsj_cOqfAZyrXss0IA0_ini0C-Io',
    appId: '1:36974916364:ios:46693494c29e08892c4f29',
    messagingSenderId: '36974916364',
    projectId: 'fir-bolt-app',
    storageBucket: 'fir-bolt-app.appspot.com',
    iosBundleId: 'com.example.boltApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjyA1hsj_cOqfAZyrXss0IA0_ini0C-Io',
    appId: '1:36974916364:ios:3d3eb28d139ebe822c4f29',
    messagingSenderId: '36974916364',
    projectId: 'fir-bolt-app',
    storageBucket: 'fir-bolt-app.appspot.com',
    iosBundleId: 'com.example.boltApp.RunnerTests',
  );
}
